# use the shared Yast defaults
inherit_from:
  - /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

# this needs more testing if we can have frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Include:
    - "library/*/src/lib/**/*.rb"

# Offense count: 5
# Configuration parameters: AllowKeywordBlockArguments.
Lint/UnderscorePrefixedVariableName:
  Exclude:
    - 'src/modules/RootPart.rb'

# Offense count: 25
Metrics/AbcSize:
  Max: 188

# Offense count: 23
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 300

# Offense count: 18
# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 6

# Offense count: 3
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 1400

# Offense count: 25
Metrics/CyclomaticComplexity:
  Max: 46

# Offense count: 27
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 300

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 400

# Offense count: 24
Metrics/PerceivedComplexity:
  Max: 55

# Offense count: 49
# Configuration parameters: EnforcedStyle.
# SupportedStyles: snake_case, camelCase
Naming/MethodName:
  Exclude:
    - 'src/clients/update_proposal.rb'
    - 'src/include/update/rootpart.rb'
    - 'src/modules/RootPart.rb'
    - 'src/modules/SUSERelease.rb'
    - 'src/modules/Update.rb'
    - 'test/update_test.rb'

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist, NameWhitelist, MethodDefinitionMacros.
# NamePrefix: is_, has_, have_
# NamePrefixBlacklist: is_, has_, have_
# NameWhitelist: is_a?
# MethodDefinitionMacros: define_method, define_singleton_method
Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'src/modules/RootPart.rb'

# Offense count: 31
# Configuration parameters: EnforcedStyle.
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  Exclude:
    - 'src/modules/RootPart.rb'
    - 'src/modules/Update.rb'

# Offense count: 17
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'src/clients/backup_proposal.rb'
    - 'src/clients/inst_backup.rb'
    - 'src/clients/inst_rootpart.rb'
    - 'src/clients/inst_update_partition.rb'
    - 'src/clients/packages_proposal.rb'
    - 'src/clients/rootpart_proposal.rb'
    - 'src/clients/run_update.rb'
    - 'src/clients/update.rb'
    - 'src/clients/update_proposal.rb'
    - 'src/include/update/rootpart.rb'
    - 'src/lib/update/clients/inst_update_partition_auto.rb'
    - 'src/modules/RootPart.rb'
    - 'src/modules/SUSERelease.rb'
    - 'src/modules/Update.rb'

# Offense count: 15
Style/MultipleComparison:
  Exclude:
    - 'src/clients/update_proposal.rb'
    - 'src/include/update/rootpart.rb'
    - 'src/modules/RootPart.rb'
    - 'src/modules/Update.rb'
