sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast-update-image .
script:
  # the "yast-travis" script is included in the base yastdevel/ruby-tw image
  # see https://github.com/yast/docker-yast-ruby-tw/blob/master/yast-travis
  - docker run -it -e TRAVIS=1 TRAVIS_JOB_ID="$TRAVIS_JOB_ID" yast-update-image yast-travis-ruby
