#!/bin/bash

if test -d $1/var/lib/YaST ; then
    /bin/rm -f $1/var/lib/YaST
fi

if test -d $1/var/lib/YaST2 ; then
    /usr/bin/find $1/var/lib/YaST2 -name "*" -a -type f -exec rm -f -- {} \;
fi

if test -d $1/var/lib/YaST2/you ; then
    /bin/rm -f $1/var/lib/YaST2/you/quickcheck
    /bin/rm -fr $1/var/lib/YaST2/you/{files,installed,mnt,scripts}
fi

