#!/bin/bash
#
# script to add missing passwd or group entries
# before update
#
# call as "fill_passd_group <target-dir>"
#
for file in passwd group ; do 
  if test -f etc/$file ; then 
    # like fillup, but : is the only separator 
    rm -f etc/$file.add 
    sort -k 1,1 -t: -u etc/$file var/adm/fillup-templates/$file.aaa_base \ 
	| sort -k 1,1 -t: etc/$file - | uniq -u > etc/$file.add 
    cat etc/$file.add >> etc/$file 
    rm -f etc/$file.add 
    # fix permissions if this script is called with strange umask 
    chmod 644 etc/$file 
  else 
    cat var/adm/fillup-templates/$file.aaa_base > etc/$file 
  fi 
done 

